services:
  - type: web
    name: music-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn music_portal.wsgi --bind 0.0.0.0:$PORT --workers 2
    plan: free
